#!/bin/bash
set -e
mkdir -p "$SNAP_COMMON/models"

snapctl set host=127.0.0.1:11434
snapctl set models="$SNAP_COMMON/models"
snapctl set origins="*://localhost"
snapctl set cuda-visible-devices=""
snapctl set flash-attention=0
snapctl set debug=0
snapctl set context-length=""
snapctl set load-timeout=""
snapctl set keep-alive=""
snapctl set kv-cache-type=""
snapctl set no-cloud=""
snapctl set max-queue=""
snapctl set max-loaded-models=""
snapctl set num-parallel=""